
export interface TutenUser {
    serviceData: string,
    userAvailability: string,
    sessionTokenBck: string,
    firstName: string,
    lastName: string,
    email: string,
    active: boolean,
    passwordHash: string,
    sessionTokenWeb: string,
    phoneNumber: string,
    agreedToTermsOfUse: boolean,
    whereKnownUs: string,
    lastLogin: string,
    sessionTokenCli: string,
    sessionTokenPro: string,
    funds: number,
    tokenFacebook: string,
    tokenGoogle: string,
    tokensIonic: string,
    photoPath: string,
    photoExt: string,
    userRole: TutenRole,
    sync: number,
    usedCodeList: string,
    referrer: string,
    rut: string,
    domain: string,
    typeProfessional: string,
    tutenSubRole: string,
    userId: number,
    appVersion: string,
    estatus: number,
    _persistence_shouldRefreshFetchGroup: boolean
};

export interface TutenRole {
    userRole: string,
    description: string,
    fatherUserRole: string,
    domain: string,
    estatus: number,
    defaultNamespace: string,
    id: number,
    _persistence_shouldRefreshFetchGroup: boolean,
};
